version: 2
jobs:
  build:
    working_directory: ~/rangle-seatmap-poc
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run test -- --watch=false --progress=false
